# Generated by Django 4.2.3 on 2024-09-26 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meeting_id', models.CharField(max_length=200)),
                ('meeting_topic', models.CharField(max_length=200)),
                ('start_time', models.DateTimeField()),
                ('is_completed', models.BooleanField(default=False)),
            ],
        ),
    ]
