# Generated by Django 4.2.3 on 2024-09-29 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meeting', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='file',
            field=models.FileField(blank=True, default=None, null=True, upload_to='uploads/'),
        ),
    ]
