# Generated by Django 4.2.3 on 2024-09-29 19:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('meeting', '0002_meeting_file'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmotionData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('emotion', models.CharField(max_length=100)),
                ('intensity', models.FloatField()),
                ('meeting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meeting.meeting')),
            ],
        ),
    ]
