# Generated by Django 4.2.3 on 2024-10-02 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meeting', '0003_emotiondata'),
    ]

    operations = [
        migrations.AddField(
            model_name='emotiondata',
            name='frame_number',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
