# Generated by Django 4.2.3 on 2024-10-02 20:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('meeting', '0004_emotiondata_frame_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='emotiondata',
            name='frame_number',
        ),
    ]
