# Generated by Django 4.2.3 on 2024-10-03 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meeting', '0005_remove_emotiondata_frame_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emotiondata',
            name='timestamp',
            field=models.FloatField(),
        ),
    ]
